"""Level-0 representation-shaped development substrates and bundles.

This experimental namespace produces model-free software-correctness
fixtures.  Its outputs are not synthetic-qualified scientific instruments and
do not authorize subject access.
"""

from .cartesian_fourier_domain_phantom import (
    CARTESIAN_FOURIER_FIXED_NULL,
    CARTESIAN_FOURIER_NO_CORE_NULL,
    CARTESIAN_FOURIER_POSITIVE,
    CARTESIAN_FOURIER_PREREQUISITE_FAILURE,
    CARTESIAN_FOURIER_RESOURCE_ESTIMATOR_ID,
    CARTESIAN_FOURIER_STATE_MIXING_ID,
    CartesianExpectedDisposition,
    CartesianFourierCase,
    CartesianFourierDomainGenerator,
    CartesianFourierDomainPhantom,
    CartesianFourierDomainSpec,
    CartesianFourierEstimatorInputs,
    CartesianFourierOracleTruth,
)
from .cartesian_fourier_estimator import (
    CARTESIAN_FOURIER_FIELD_ESTIMATOR_ID,
    CARTESIAN_FOURIER_FIELD_RECEIPT_VERSION,
    CartesianFourierEstimatorError,
    CartesianFourierFieldEstimate,
    estimate_cartesian_fourier_field,
)
from .generators import (
    GENERATOR_FAMILY_IDENTITY_SCHEMA_VERSION,
    GeneratorFamilyContractError,
    GeneratorFamilyIdentity,
    GeneratorProtocol,
    representation_phantom_family_identity,
    require_distinct_construction_families,
)
from .phantom_bundle import (
    EmittedRepresentationPhantomBundle,
    RepresentationPhantomBundleError,
    emit_representation_phantom_bundle,
)
from .protocol import (
    REPRESENTATION_PHANTOM_PROTOCOL_SCHEMA_VERSION,
    LoadedRepresentationPhantomProtocol,
    RepresentationPhantomProtocol,
    RepresentationPhantomProtocolError,
    RepresentationPhantomProtocolIntegrityError,
    RepresentationPhantomProtocolSchemaError,
    load_representation_phantom_protocol,
)
from .representation_estimator import (
    REPRESENTATION_ESTIMATOR_INPUT_RECEIPT_VERSION,
    REPRESENTATION_FIELD_ESTIMATE_RECEIPT_VERSION,
    REPRESENTATION_FIELD_ESTIMATOR_ID,
    RepresentationEstimatorError,
    RepresentationEstimatorInputs,
    RepresentationFieldEstimate,
    build_representation_estimator_inputs,
    estimate_representation_field,
)
from .representation_phantom import (
    ANGULAR_SECTION_POSITIVE,
    FIXED_DIRECTION_NULL,
    PhantomCase,
    RepresentationPhantom,
    RepresentationPhantomSpec,
)
from .spectral_moment_phantom import (
    SPECTRAL_MOMENT_FIXED_NULL,
    SPECTRAL_MOMENT_PHANTOM_RECEIPT_VERSION,
    SPECTRAL_MOMENT_POSITIVE,
    SPECTRAL_MOMENT_PREREQUISITE_FAILURE,
    ExpectedControlDisposition,
    SpectralMomentCase,
    SpectralMomentEstimatorInputs,
    SpectralMomentGenerator,
    SpectralMomentOracleTruth,
    SpectralMomentPhantom,
    SpectralMomentPhantomSpec,
)

__all__ = [
    "ANGULAR_SECTION_POSITIVE",
    "CARTESIAN_FOURIER_FIELD_ESTIMATOR_ID",
    "CARTESIAN_FOURIER_FIELD_RECEIPT_VERSION",
    "CARTESIAN_FOURIER_FIXED_NULL",
    "CARTESIAN_FOURIER_NO_CORE_NULL",
    "CARTESIAN_FOURIER_POSITIVE",
    "CARTESIAN_FOURIER_PREREQUISITE_FAILURE",
    "CARTESIAN_FOURIER_RESOURCE_ESTIMATOR_ID",
    "CARTESIAN_FOURIER_STATE_MIXING_ID",
    "FIXED_DIRECTION_NULL",
    "GENERATOR_FAMILY_IDENTITY_SCHEMA_VERSION",
    "REPRESENTATION_ESTIMATOR_INPUT_RECEIPT_VERSION",
    "REPRESENTATION_FIELD_ESTIMATE_RECEIPT_VERSION",
    "REPRESENTATION_FIELD_ESTIMATOR_ID",
    "REPRESENTATION_PHANTOM_PROTOCOL_SCHEMA_VERSION",
    "SPECTRAL_MOMENT_FIXED_NULL",
    "SPECTRAL_MOMENT_PHANTOM_RECEIPT_VERSION",
    "SPECTRAL_MOMENT_POSITIVE",
    "SPECTRAL_MOMENT_PREREQUISITE_FAILURE",
    "CartesianExpectedDisposition",
    "CartesianFourierCase",
    "CartesianFourierDomainGenerator",
    "CartesianFourierDomainPhantom",
    "CartesianFourierDomainSpec",
    "CartesianFourierEstimatorError",
    "CartesianFourierEstimatorInputs",
    "CartesianFourierFieldEstimate",
    "CartesianFourierOracleTruth",
    "EmittedRepresentationPhantomBundle",
    "ExpectedControlDisposition",
    "GeneratorFamilyContractError",
    "GeneratorFamilyIdentity",
    "GeneratorProtocol",
    "LoadedRepresentationPhantomProtocol",
    "PhantomCase",
    "RepresentationEstimatorError",
    "RepresentationEstimatorInputs",
    "RepresentationFieldEstimate",
    "RepresentationPhantom",
    "RepresentationPhantomBundleError",
    "RepresentationPhantomProtocol",
    "RepresentationPhantomProtocolError",
    "RepresentationPhantomProtocolIntegrityError",
    "RepresentationPhantomProtocolSchemaError",
    "RepresentationPhantomSpec",
    "SpectralMomentCase",
    "SpectralMomentEstimatorInputs",
    "SpectralMomentGenerator",
    "SpectralMomentOracleTruth",
    "SpectralMomentPhantom",
    "SpectralMomentPhantomSpec",
    "build_representation_estimator_inputs",
    "emit_representation_phantom_bundle",
    "estimate_cartesian_fourier_field",
    "estimate_representation_field",
    "load_representation_phantom_protocol",
    "representation_phantom_family_identity",
    "require_distinct_construction_families",
]
