"""Experimental metadata contracts for the order-parameter-first instrument.

This namespace validates identities and manifests only.  Importing it does not
load model frameworks, dereference payloads, run estimators, or authorize
subject access.  The API is provisional before SpiralLens 1.0.
"""

from __future__ import annotations

from .artifact_loader import (
    InstrumentArtifactIntegrityError,
    InstrumentArtifactSchemaError,
    LoadedInstrumentArtifact,
    load_instrument_artifact,
)
from .artifacts import (
    CalibrationConfirmationResult,
    CalibrationSelectionDecision,
    CandidateGraph,
    CoreCandidate,
    CoreScore,
    DefectCoordinateBinding,
    DefectLocalizationBinding,
    DefectLoopEstimate,
    EdgeConnection,
    ExplicitCoreGraphBinding,
    GeometricFieldEstimate,
    GeometryLoopEstimate,
    GraphConstructionSpec,
    GraphFreeBinding,
    GroundTruthAnchor,
    HypothesisDecision,
    HypothesisFixedChoice,
    HypothesisResolvedChoice,
    HypothesisRuleChoice,
    InheritedFieldGraphBinding,
    OrderParameterField,
    OrderParameterSpec,
    SubstrateBinding,
    SupportDiagnostic,
    instrument_artifact_from_dict,
)
from .canonical import (
    CanonicalJsonError,
    canonical_json_bytes,
    canonical_json_sha256,
    parse_canonical_json,
)
from .common import (
    ARTIFACT_SCHEMA_VERSION_BY_TYPE,
    ArtifactRef,
    ArtifactType,
    ClaimLevel,
    ContractValidationError,
    EvolutionAxis,
    FitRole,
    GateState,
    HypothesisDisposition,
    HypothesisId,
    NeighborhoodMode,
    PayloadKind,
    PayloadRef,
    ResolutionState,
    RuleChoice,
    ScientificBranch,
)
from .registry import (
    HistoricalSelectionBoundary,
    HypothesisRegistry,
    HypothesisRegistryError,
    HypothesisRegistryPolicyError,
    HypothesisSpec,
    validate_p0_registry,
)
from .registry_loader import (
    HypothesisRegistryIntegrityError,
    HypothesisRegistrySchemaError,
    LoadedHypothesisRegistry,
    hypothesis_registry_from_dict,
    load_hypothesis_registry,
)

__all__ = [
    "ARTIFACT_SCHEMA_VERSION_BY_TYPE",
    "ArtifactRef",
    "ArtifactType",
    "CalibrationConfirmationResult",
    "CalibrationSelectionDecision",
    "CandidateGraph",
    "CanonicalJsonError",
    "ClaimLevel",
    "ContractValidationError",
    "CoreCandidate",
    "CoreScore",
    "DefectCoordinateBinding",
    "DefectLocalizationBinding",
    "DefectLoopEstimate",
    "EdgeConnection",
    "EvolutionAxis",
    "ExplicitCoreGraphBinding",
    "FitRole",
    "GateState",
    "GeometricFieldEstimate",
    "GeometryLoopEstimate",
    "GraphConstructionSpec",
    "GraphFreeBinding",
    "GroundTruthAnchor",
    "HistoricalSelectionBoundary",
    "HypothesisDecision",
    "HypothesisFixedChoice",
    "HypothesisResolvedChoice",
    "HypothesisRuleChoice",
    "HypothesisDisposition",
    "HypothesisId",
    "HypothesisRegistry",
    "HypothesisRegistryError",
    "HypothesisRegistryIntegrityError",
    "HypothesisRegistryPolicyError",
    "HypothesisRegistrySchemaError",
    "HypothesisSpec",
    "InheritedFieldGraphBinding",
    "InstrumentArtifactIntegrityError",
    "InstrumentArtifactSchemaError",
    "LoadedHypothesisRegistry",
    "LoadedInstrumentArtifact",
    "NeighborhoodMode",
    "OrderParameterField",
    "OrderParameterSpec",
    "PayloadKind",
    "PayloadRef",
    "ResolutionState",
    "RuleChoice",
    "ScientificBranch",
    "SubstrateBinding",
    "SupportDiagnostic",
    "canonical_json_bytes",
    "canonical_json_sha256",
    "hypothesis_registry_from_dict",
    "instrument_artifact_from_dict",
    "load_hypothesis_registry",
    "load_instrument_artifact",
    "parse_canonical_json",
    "validate_p0_registry",
]
